name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not dev
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Pull requests to main are only allowed from dev branch."
            exit 1
          fi
